/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'slotTime' : IDL.Text,
  'issue' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getBookedSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'slotTime' : IDL.Text,
    'issue' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getBookedSlots' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };